# 00-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fintech-cluster
  region: us-east-1 # Asegúrate que coincida con tu región
  version: "1.28"

nodeGroups:
  - name: ng-fintech-workers
    instanceType: t3.medium
    desiredCapacity: 2